parameters:
#    jburetweb.example.class: jburet\webBundle\Example

services:
#    jburetweb.example:
#        class: %jburetweb.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
